version: '2'

services:

### App Container ######################################

    rate_app:
        container_name: rate_app
        build:
            context: .
        volumes:
            - "./data.db:/usr/src/app/data.db"
        ports:
            - "8080:5000"
