"""user, email

Revision ID: eba2a03f6672
Revises: 1d6523fbf2ad
Create Date: 2019-07-01 12:20:28.149836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eba2a03f6672'
down_revision = '1d6523fbf2ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_model', sa.Column('email', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_model', 'email')
    # ### end Alembic commands ###
